### ISSUE TITLE
Ubuntu 17.10 and python 3.6.3 will not compile

### ISSUE THREAD

**Issue by celtichawk** [libaudioverse/libaudioverse#37]
I've run into this on a brand new Ubuntu 17.10 install.

1. It is a 64 bit install, using the dependancies listed in the platform specific instructions

2. I made sure all the packages were up to date to the most recent versions.

3. I did cmake .. and it sucessfully ran that.

4. When I do make or sudo make, it gets to 85% of the make process and begins building bindings, then generates a traceback

Tracebac:

[ 85%] Built target libaudioverse_cfiles
Building bindings...
Traceback (most recent call last):
  File "/home/jace/libaudioverse/scripts/build_bindings.py", line 12, in <module>
    bindings.make_bindings.make_bindings()
  File "/home/jace/libaudioverse/bindings/make_bindings.py", line 50, in make_bindings
    files = generator(copy.deepcopy(all_info))
  File "/home/jace/libaudioverse/bindings/python/__init__.py", line 168, in make_python
    'libaudioverse/__init__.py': env.get_template('libaudioverse/__init__.py.t').render(context).encode('utf8'),
  File "/home/jace/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/jace/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jace/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jace/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jace/libaudioverse/bindings/python/libaudioverse/__init__.py.t", line 34, in top-level template code
    {%set constants_prefix = common_prefix(constants.keys())%}
  File "/home/jace/libaudioverse/bindings/transformers.py", line 55, in common_prefix
    return os.path.commonprefix(l)
  File "/usr/lib/python3.6/genericpath.py", line 76, in commonprefix
    if not isinstance(m[0], (list, tuple)):
TypeError: 'odict_keys' object does not support indexing
CMakeFiles/libaudioverse_bindings.dir/build.make:57: recipe for target 'CMakeFiles/libaudioverse_bindings' failed
make[2]: *** [CMakeFiles/libaudioverse_bindings] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/libaudioverse_bindings.dir/all' failed
make[1]: *** [CMakeFiles/libaudioverse_bindings.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

This happens regardless of package versions, and I am using the latest git commit, with the latest Python version, 3.6.3, the default on my system.

**Comment by mmxgn** [comment]
Fixed it by changing line 55 of `bindings/transformers.py` from:

`return os.path.commonprefix(l)`

to:

`return os.path.commonprefix(list(l))`
